### ISSUE TITLE
coresdns is still labeled as kube-dns

### ISSUE THREAD

**Issue by idanlevin** [coredns/deployment#116]
Hi Guys,

I wonder why the coredns deployment still has `k8s-app: kube-dns` instead of `k8s-app: coredns`?

For example the `prometheus-operator` is looking for coredns using `k8s-app: coredns` but obviously it fails to find it.

Any reason for this?

**Comment by miekg** [comment]
I believe this was done because of backwards compatibility.

**Comment by idanlevin** [comment]
@miekg do we know what will break if we change it? any way we can validate that's not a mistake? or are there plans to eventually change it?

**Comment by miekg** [comment]
Why do we need to change it?

**Comment by tariq1890** [comment]
My two cents: I think this issue does raise a good question of how we maintain dependencies here. It's certainly misleading when we use `kube-dns` as label selectors when `kube-dns` is intended to be phased out by `coredns`

**Comment by miekg** [comment]
Not disputing that, but they are some tradeoffs (like backwards
compatibility). At some point though, naming the thing coredns makes sense.
How we get there in a sane way is the question.

**Comment by idanlevin** [comment]
maybe we could introduce a new service while keeping the old one for a while:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: kube-system
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
  labels:
    k8s-app: coredns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: CLUSTER_DNS_IP
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: metrics
    port: 9153
    protocol: TCP
```

this way, applications looking for `coredns` service can use `k8s-app: coredns`.

then we probably should decide on a date/release where we deprecate the old `kube-dns` service and change the `k8s-app` label of the pods to `coredns`

WDYT?
