### ISSUE TITLE
Kubernetes manifest need rework

### ISSUE THREAD

**Issue by Quentin-M** [coredns/deployment#13]
Hi,

I was evaluating using CoreDNS rather than the deprecated kube-dns addon, as now suggested by Kubernetes. However, I found a few issues in the provided manifests:
 
- It is not clear at first glance which manifest should be used: `coredns.yaml.sed`, `coredns-1.6.yaml.sed`? We are now on Kubernetes 1.8 and soon 1.9. In my understanding, `coredns.yaml.sed` should be renamed `coredns-1.5.yaml.sed` and `coredns-1.6.yaml.sed` should simply be `coredns.yaml.sed`, or even better: the RBAC resource should be separated (like most projects do).
- coredns-1.6.yaml.sed has an invalid ConfigMap (cidrs)
- The `kubernetes.io/cluster-service` label has been deprecated, and was only useful to the Addon Manager
- `scheduler.alpha.kubernetes.io/tolerations` has been replaced by an actual spec element (see bel0w_.
- Tolerations should contain the standardized master taint / label (see below)
- For stability and security purposes (especially with the Node Authorizer admission controller), CoreDNS should only run on master nodes (and should probably have at least 2 replicas by default).
- The deployment should have a RollingUpdate strategy for availability purposes.
- Using the `latest` image is generally considered bad practice.
- Exposing the metrics port on the service can arguably be considered a threat (especially if Network Policies are being used).

The Kubernetes [documentation](https://kubernetes.io/docs/concepts/cluster-administration/addons/) deprecated most of the cluster addons (even the well-known kubedns), and now lists a very few addons, including CoreDNS (pointing to that repository). However:
- The manifest does not seem to be strongly maintained
- The main repository's README file mentions: `If you do want to use CoreDNS in production, please let us know.`
This is a little bit worrying considering thousands users refer to that documentation as a reference, including numerous companies, which sometimes run hundreds/thousands clusters.

_Tolerating and selecting the master nodes_
```
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
        - key: "CriticalAddonsOnly"
          operator: "Exists"
      nodeSelector:
        node-role.kubernetes.io/master: ""
```

_Rolling-Update strategy_
```
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
```

Thank you.
