### ISSUE TITLE
Revisit pod node anti-affinity rules

### ISSUE THREAD

**Issue by jmcmeek** [coredns/deployment#197]
pod anti-affinity rules were revoked in https://github.com/coredns/deployment/pull/60 due to Kubernetes scheduler performance concerns.

Scheduler performance enhancements have been made since then and I think it is safe to use those now.  See my question and reply on #sig-scheduler Slack channel
Q: https://kubernetes.slack.com/archives/C09TP78DV/p1568127000040100
R: https://kubernetes.slack.com/archives/C09TP78DV/p1568128953041900

**Comment by jmcmeek** [comment]
Also, should this include zone anti-affinty?  Something like
```
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: k8s-app
                  operator: In
                  values: ["kube-dns"]
              topologyKey: failure-domain.beta.kubernetes.io/zone
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: k8s-app
                  operator: In
                  values: ["kube-dns"]
              topologyKey: "kubernetes.io/hostname"
```
