### ISSUE TITLE
Add lameduck to recommend Kubernetes deployment configuration

### ISSUE THREAD

**Issue by rtheis** [coredns/deployment#199]
Related to https://github.com/coredns/coredns/issues/2984, `lameduck` should be added to the recommend Kubernetes deployment configuration.  Adding `lameduck` to the `health` plugin minimizes DNS resolution failures during a CoreDNS pod restart or deployment rollout.  This does come at the expense of increased rollout times.  For HA environments, this trade-off is likely acceptable.

One can test this proposed change by running `kubectl rollout restart deployment -n kube-system coredns` followed by `kubectl rollout status deployment -n kube-system coredns` while monitoring errors from the `dnstools` pod created by the deployment listed below.  A `lameduck` anywhere from 5 to 10 seconds eliminates most DNS resolution failures.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: dnstools
  name: dnstools
  namespace: default
spec:
  selector:
    matchLabels:
      run: dnstools
  template:
    metadata:
      labels:
        run: dnstools
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - while true; do curl -sk --max-time 10 --connect-timeout 7 https://kubernetes.default.svc.cluster.local/version || echo ERROR at $(date) ; sleep 0.1 ; done
        image: infoblox/dnstools:v3
        name: dnstools
```

CoreDNS version: 1.6.2
Corefile:

```
    .:53 {
        errors
        health {
            lameduck 10s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```
