### ISSUE TITLE
kubernetes: readinessProbe

### ISSUE THREAD

**Issue by chrisohaver** [coredns/deployment#63]
Look into adding a readinessProbe to the deployment.  Probably something similar to `livenessProbe` like...

```
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
```
As of now, it may be redundant with livenessProbe, since we don't (as of yet) ever go "unready" after becoming ready.  But without the readinessProbe, k8s may be reporting that a coredns pod is ready before it is actually becomes healthy.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
